const PRODUCTS=[
{id:1,name:'Lámpara Alba',category:'Iluminación',price:84900,badge:'Nuevo',stock:6,material:'Lino · metal',image:'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=900&q=85',description:'Lámpara de mesa de luz cálida, pantalla textil y base de líneas suaves. Pensada para rincones de lectura y mesas de noche.',options:['Arena','Hueso','Oliva']},
{id:2,name:'Manta Bruma',category:'Textiles',price:52900,badge:'Favorita',stock:11,material:'Algodón lavado',image:'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=900&q=85',description:'Manta liviana de trama relajada y tacto suave. Una capa simple para sumar textura al sillón o al pie de cama.',options:['Crudo','Arcilla','Gris piedra']},
{id:3,name:'Jarrón Terral',category:'Cerámica',price:38900,badge:'Artesanal',stock:4,material:'Cerámica mate',image:'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=900&q=85',description:'Jarrón escultórico de superficie mate y silueta orgánica. Cada pieza de la demo conserva pequeñas variaciones visuales.',options:['Natural','Carbón']},
{id:4,name:'Mesa Ladera',category:'Muebles',price:198000,badge:'Edición corta',stock:3,material:'Madera maciza',image:'https://images.unsplash.com/photo-1532372320572-cda25653a694?auto=format&fit=crop&w=900&q=85',description:'Mesa auxiliar compacta con veta protagonista y terminación natural. Funciona junto al sofá, la cama o como apoyo de lectura.',options:['Roble claro','Nogal']},
{id:5,name:'Cuenco Origen',category:'Cerámica',price:26900,badge:'',stock:14,material:'Gres esmaltado',image:'https://images.unsplash.com/photo-1610701596061-2ecf227e85b2?auto=format&fit=crop&w=900&q=85',description:'Cuenco de gres para servir, guardar o simplemente dejar a la vista. Bordes suaves y esmalte de aspecto mineral.',options:['Arena','Musgo','Tiza']},
{id:6,name:'Almohadón Siesta',category:'Textiles',price:31900,badge:'',stock:9,material:'Lino texturado',image:'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=900&q=85',description:'Almohadón de lino con textura visible y relleno mullido. Diseñado para combinar tonos neutros sin volver plano el espacio.',options:['Avena','Terracota','Verde seco']},
{id:7,name:'Aplique Niebla',category:'Iluminación',price:72900,badge:'Nuevo',stock:5,material:'Metal · vidrio',image:'https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=900&q=85',description:'Aplique de pared de luz difusa, perfecto para dormitorios, pasillos o rincones que piden una iluminación más íntima.',options:['Latón','Negro mate']},
{id:8,name:'Banco Sur',category:'Muebles',price:129000,badge:'',stock:2,material:'Madera · tejido',image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=85',description:'Banco bajo de proporciones simples y asiento tejido. Una pieza versátil para recibidores, dormitorios o espacios de paso.',options:['Natural','Tostado']}
];

const STORAGE={cart:'casa_nomada_cart_v1',favorites:'casa_nomada_favorites_v1'};
let cart=load(STORAGE.cart,[]),favorites=load(STORAGE.favorites,[]),category='Todos',sort='featured',searchTerm='',coupon=false,currentProduct=null,currentOption='';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const els={grid:$('#product-grid'),tabs:$('#category-tabs'),count:$('#product-count'),sort:$('#sort-select'),activeFilter:$('#active-filter'),cartDrawer:$('#cart-drawer'),favDrawer:$('#favorites-drawer'),overlay:$('#drawer-overlay'),cartItems:$('#cart-items'),favItems:$('#favorite-items'),cartCount:$('#cart-count'),favoriteCount:$('#favorite-count'),subtotal:$('#cart-subtotal'),discount:$('#cart-discount'),discountRow:$('#discount-row'),total:$('#cart-total'),productModal:$('#product-modal'),modalMedia:$('#product-modal-media'),modalCopy:$('#product-modal-copy'),checkoutModal:$('#checkout-modal'),checkoutSummary:$('#checkout-summary'),checkoutForm:$('#checkout-form'),orderSuccess:$('#order-success'),toast:$('#toast'),searchPanel:$('#search-panel'),search:$('#global-search'),mobileMenu:$('#mobile-menu')};

init();
function init(){renderTabs();renderProducts();renderFeatured();renderCart();renderFavorites();bindUI();}

function bindUI(){
 $('#cart-toggle').onclick=()=>openDrawer('cart'); $('#favorites-toggle').onclick=()=>openDrawer('favorites');
 $$('[data-close-drawer]').forEach(b=>b.onclick=closeDrawers); $$('[data-close-favorites]').forEach(b=>b.onclick=closeDrawers); els.overlay.onclick=closeDrawers;
 $('#search-toggle').onclick=()=>{els.searchPanel.hidden=false;setTimeout(()=>els.search.focus(),10)}; $('#search-close').onclick=()=>els.searchPanel.hidden=true;
 els.search.addEventListener('input',e=>{searchTerm=e.target.value.trim().toLowerCase();category='Todos';renderTabs();renderProducts();if(searchTerm)document.querySelector('#catalogo').scrollIntoView({behavior:'smooth'})});
 $('#menu-toggle').onclick=()=>els.mobileMenu.hidden=!els.mobileMenu.hidden; els.mobileMenu.querySelectorAll('a').forEach(a=>a.onclick=()=>els.mobileMenu.hidden=true);
 els.sort.onchange=e=>{sort=e.target.value;renderProducts()}; $('#reset-filters').onclick=()=>{category='Todos';searchTerm='';els.search.value='';sort='featured';els.sort.value='featured';renderTabs();renderProducts()};
 $$('.collection-card').forEach(card=>card.onclick=()=>{category=card.dataset.categoryJump;searchTerm='';renderTabs();renderProducts();$('#catalogo').scrollIntoView({behavior:'smooth'})});
 $('#coupon-button').onclick=applyCoupon; $('#checkout-button').onclick=openCheckout;
 $$('[data-close-modal]').forEach(b=>b.onclick=()=>closeModal(b.dataset.closeModal)); $$('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));
 $('#newsletter-form').onsubmit=e=>{e.preventDefault();e.target.reset();toast('Suscripción demo registrada')};
 els.checkoutForm.onsubmit=finishOrder;
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDrawers();els.searchPanel.hidden=true;$$('.modal-backdrop').forEach(m=>m.hidden=true);document.body.classList.remove('no-scroll')}});
}

function renderTabs(){const cats=['Todos',...new Set(PRODUCTS.map(p=>p.category))];els.tabs.innerHTML=cats.map(c=>`<button class="${c===category?'active':''}" data-cat="${c}">${c}</button>`).join('');els.tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderTabs();renderProducts()})}
function filteredProducts(){let list=PRODUCTS.filter(p=>(category==='Todos'||p.category===category)&&(!searchTerm||`${p.name} ${p.category} ${p.material}`.toLowerCase().includes(searchTerm)));if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));return list}
function renderProducts(){const list=filteredProducts();els.grid.innerHTML=list.length?list.map(productCard).join(''):`<div class="empty-drawer" style="grid-column:1/-1"><strong>No encontramos esa pieza</strong><p>Probá con otra categoría o búsqueda.</p></div>`;els.count.textContent=`${list.length} ${list.length===1?'pieza':'piezas'}`;els.activeFilter.hidden=!searchTerm;els.activeFilter.textContent=searchTerm?`Resultados para “${searchTerm}”`:'';bindProductCards()}
function productCard(p){return `<article class="product-card"><div class="product-media"><img src="${p.image}" alt="${p.name}" loading="lazy"><button class="favorite-button ${favorites.includes(p.id)?'active':''}" data-favorite="${p.id}" aria-label="Guardar ${p.name}">${favorites.includes(p.id)?'♥':'♡'}</button>${p.badge?`<span class="product-badge">${p.badge}</span>`:''}<button class="product-open" data-open-product="${p.id}" aria-label="Ver ${p.name}"></button></div><div class="product-info"><div class="product-meta"><h3>${p.name}</h3><span class="product-price">${money(p.price)}</span></div><div class="product-sub"><span>${p.category}</span><span>${p.material}</span></div></div></article>`}
function bindProductCards(){els.grid.querySelectorAll('[data-open-product]').forEach(b=>b.onclick=()=>openProduct(+b.dataset.openProduct));els.grid.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFavorite(+b.dataset.favorite)})}

function renderFeatured(){const chosen=[PRODUCTS[0],PRODUCTS[3],PRODUCTS[5]];$('#featured-row').innerHTML=chosen.map(p=>`<article class="featured-card"><img src="${p.image}" alt="${p.name}" loading="lazy"><div><span class="eyebrow">${p.category}</span><h3>${p.name}</h3><p>${p.description.slice(0,92)}...</p><button data-featured="${p.id}">Ver pieza →</button></div></article>`).join('');$('#featured-row').querySelectorAll('[data-featured]').forEach(b=>b.onclick=()=>openProduct(+b.dataset.featured))}

function openProduct(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;currentProduct=p;currentOption=p.options[0];els.modalMedia.innerHTML=`<img src="${p.image}" alt="${p.name}">`;els.modalCopy.innerHTML=`<span class="product-category">${p.category}</span><h2 id="product-modal-title">${p.name}</h2><div class="modal-price">${money(p.price)}</div><p>${p.description}</p><div class="option-group"><label>Terminación</label><div class="option-row">${p.options.map((o,i)=>`<button class="${i===0?'active':''}" data-option="${o}" type="button">${o}</button>`).join('')}</div></div><div class="stock-note">● ${p.stock} unidades demo disponibles</div><button class="button dark full" id="modal-add-cart" type="button">Agregar a la bolsa</button><button class="text-link" id="modal-favorite" type="button" style="margin-top:18px">${favorites.includes(p.id)?'Quitar de favoritos':'♡ Guardar en favoritos'}</button>`;els.modalCopy.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{currentOption=b.dataset.option;els.modalCopy.querySelectorAll('[data-option]').forEach(x=>x.classList.toggle('active',x===b))});$('#modal-add-cart').onclick=()=>{addToCart(p.id,currentOption);closeModal('product-modal');openDrawer('cart')};$('#modal-favorite').onclick=()=>{toggleFavorite(p.id);openProduct(p.id)};els.productModal.hidden=false;document.body.classList.add('no-scroll')}

function addToCart(id,option){const existing=cart.find(i=>i.id===id&&i.option===option);existing?existing.qty++:cart.push({id,option,qty:1});save(STORAGE.cart,cart);renderCart();toast('Agregado a la bolsa')}
function updateQty(index,delta){cart[index].qty+=delta;if(cart[index].qty<=0)cart.splice(index,1);save(STORAGE.cart,cart);renderCart()}
function removeCart(index){cart.splice(index,1);save(STORAGE.cart,cart);renderCart()}
function renderCart(){const qty=cart.reduce((s,i)=>s+i.qty,0);els.cartCount.textContent=qty;els.cartItems.innerHTML=cart.length?cart.map((item,index)=>{const p=PRODUCTS.find(x=>x.id===item.id);return `<div class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>${item.option}</p><div class="qty-control"><button data-minus="${index}">−</button><span>${item.qty}</span><button data-plus="${index}">+</button></div><button class="remove-link" data-remove="${index}">Quitar</button></div><span class="cart-price">${money(p.price*item.qty)}</span></div>`}).join(''):`<div class="empty-drawer"><strong>Tu bolsa está vacía</strong><p>Elegí alguna pieza del catálogo para empezar.</p></div>`;els.cartItems.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>updateQty(+b.dataset.minus,-1));els.cartItems.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>updateQty(+b.dataset.plus,1));els.cartItems.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeCart(+b.dataset.remove));updateTotals()}
function subtotal(){return cart.reduce((sum,i)=>{const p=PRODUCTS.find(x=>x.id===i.id);return sum+p.price*i.qty},0)}
function updateTotals(){const sub=subtotal(),disc=coupon?Math.round(sub*.1):0;els.subtotal.textContent=money(sub);els.discount.textContent=`-${money(disc)}`;els.discountRow.hidden=!coupon;els.total.textContent=money(sub-disc);$('#checkout-button').disabled=!cart.length}
function applyCoupon(){const value=$('#coupon-input').value.trim().toUpperCase();if(value==='NOMADA10'){coupon=true;updateTotals();toast('Cupón demo aplicado: 10%')}else toast('Probá el código demo NOMADA10')}

function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save(STORAGE.favorites,favorites);renderFavorites();renderProducts();toast(favorites.includes(id)?'Guardado en favoritos':'Quitado de favoritos')}
function renderFavorites(){els.favoriteCount.textContent=favorites.length;const list=favorites.map(id=>PRODUCTS.find(p=>p.id===id)).filter(Boolean);els.favItems.innerHTML=list.length?list.map(p=>`<div class="favorite-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>${p.category} · ${money(p.price)}</p><button class="remove-link" data-fav-open="${p.id}">Ver pieza</button></div><button class="remove-link" data-fav-remove="${p.id}">Quitar</button></div>`).join(''):`<div class="empty-drawer"><strong>Todavía no guardaste nada</strong><p>Usá el corazón para armar tu selección.</p></div>`;els.favItems.querySelectorAll('[data-fav-open]').forEach(b=>b.onclick=()=>{closeDrawers();openProduct(+b.dataset.favOpen)});els.favItems.querySelectorAll('[data-fav-remove]').forEach(b=>b.onclick=()=>toggleFavorite(+b.dataset.favRemove))}

function openDrawer(type){closeDrawers();els.overlay.hidden=false;(type==='cart'?els.cartDrawer:els.favDrawer).classList.add('open');(type==='cart'?els.cartDrawer:els.favDrawer).setAttribute('aria-hidden','false');document.body.classList.add('no-scroll')}
function closeDrawers(){[els.cartDrawer,els.favDrawer].forEach(d=>{d.classList.remove('open');d.setAttribute('aria-hidden','true')});els.overlay.hidden=true;if(els.productModal.hidden&&els.checkoutModal.hidden)document.body.classList.remove('no-scroll')}

function openCheckout(){if(!cart.length)return;closeDrawers();renderCheckoutSummary();els.checkoutForm.hidden=false;els.orderSuccess.hidden=true;els.checkoutModal.hidden=false;document.body.classList.add('no-scroll')}
function renderCheckoutSummary(){const sub=subtotal(),disc=coupon?Math.round(sub*.1):0;els.checkoutSummary.innerHTML=`<h3>Resumen</h3>${cart.map(i=>{const p=PRODUCTS.find(x=>x.id===i.id);return `<div><span>${p.name} × ${i.qty}</span><strong>${money(p.price*i.qty)}</strong></div>`}).join('')}<div><span>Subtotal</span><strong>${money(sub)}</strong></div>${coupon?`<div><span>Cupón NOMADA10</span><strong>-${money(disc)}</strong></div>`:''}<div style="border-top:1px solid var(--line);margin-top:8px;padding-top:12px"><span>Total demo</span><strong>${money(sub-disc)}</strong></div>`}
function finishOrder(e){e.preventDefault();const data=new FormData(e.target),shipping=Number(data.get('shipping')||0),sub=subtotal(),disc=coupon?Math.round(sub*.1):0,total=sub-disc+shipping,order=`CN-${Math.floor(1000+Math.random()*8999)}`;els.checkoutForm.hidden=true;els.orderSuccess.hidden=false;els.orderSuccess.innerHTML=`<span style="font-size:36px">✓</span><strong>Pedido demo confirmado</strong><p>Número ${order}<br>Total simulado: ${money(total)}<br><br>No se procesó ningún pago ni se enviaron datos a un servidor.</p><button class="button dark" id="finish-demo" type="button">Volver a la tienda</button>`;$('#finish-demo').onclick=()=>{cart=[];coupon=false;save(STORAGE.cart,cart);renderCart();e.target.reset();closeModal('checkout-modal');toast('Demo reiniciada para una nueva compra')}}
function closeModal(id){const modal=document.getElementById(id);if(modal)modal.hidden=true;if(!els.cartDrawer.classList.contains('open')&&!els.favDrawer.classList.contains('open'))document.body.classList.remove('no-scroll')}

function money(value){return new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(value)}
function load(key,fallback){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
let toastTimer;function toast(message){clearTimeout(toastTimer);els.toast.textContent=message;els.toast.classList.add('show');toastTimer=setTimeout(()=>els.toast.classList.remove('show'),2200)}